### ISSUE TITLE
How to `disable` the collapsible behavior programmatically?

### ISSUE THREAD

**Issue by uraniumreza** [glennflanagan/vue-collapsible#23]
So, I have two states; `view` and `edit`. In the view mode, I don't want collapsible behavior. But in the edit mode, I need to turn this on. I checked the doc, there's no prop to achieve this.

**Comment by glennflanagan** [comment]
Sound like something out of scope for this component - it sounds like you want to render a different component based on the state. Or just set `isOpen` to true when in the view mode.

**Comment by uraniumreza** [comment]
Hi @glennflanagan
We can definitely set `isOpen` to `true` in the view mode; but still the `onClick` handler triggers, and change the open/close state. I created this small PR, you can have a look - https://github.com/glennflanagan/vue-collapsible/pull/24
